services:
  nginx:
    image: 'nginx:alpine'
    ports:
      - '8080:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro,z
      - ./src:/var/www/laravel:z
    depends_on:
      - php
      - mysql
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel:z
    user: "${UID}:${GID}"

  mysql:
    image: 'mysql:8.0'
    ports:
      - '3316:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql:z

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/laravel:z
    user: "${UID}:${GID}"

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel:z
    user: "${UID}:${GID}"

  node:
    image: 'node:20-alpine'
    ports:
      - "5173:5173"
    working_dir: /var/www/laravel
    volumes:
      - ./src:/var/www/laravel:z
    command: npm run dev -- --host
    user: "${UID}:${GID}"

volumes:
  mysql_data: